### ISSUE TITLE
More Store info

### ISSUE THREAD

**Issue by steveberrill** [Siteation/magento2-storeinfo#2]
not really an issue but would be useful to get other store info such as Store ID, Store Code etc

**Comment by GrimLink** [comment]
Hi @steveberrill,

Why would it be useful to show the Store ID and Store Code on the frontend for you customers?

**Comment by steveberrill** [comment]
So I can use it for condition in the .phtml file.

**Comment by GrimLink** [comment]
@steveberrill,

The Storeinfo module was designed to get information that store owners can already manage in the Stores → Configuration page. This module only gathers data found in the Stores → Configuration page with the focus on the general information, such as email address, phone number, and address.

So, in short, this module is only used for displaying your store's email, phone, and address. The options you are proposing are not part of the Stores → Configuration page and would not fit the goal of the Storeinfo module.

I hope this explanation is helpful. Please let me know if you have any other questions.
